name: Compilar Roma Gerenciamento APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Cordova
        run: |
          npm install -g cordova

      - name: Criar Projeto Cordova e Compilar
        run: |
          cordova create build_app com.roma.gerenciamento "gerenciamento-roma"
          cp index.html build_app/www/
          
          # Configura o icone do aplicativo e copia a logo para o app
          if [ -f "icon.jpg" ]; then
            cp icon.jpg build_app/www/icon.jpg
            sed -i '/<\/widget>/i \    <icon src="www/icon.jpg" />' build_app/config.xml
          fi

          cd build_app
          cordova platform add android
          cordova build android --verbose

      - name: Enviar APK para Downloads
        uses: actions/upload-artifact@v4
        with:
          name: gerenciamento-roma-APK
          path: build_app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
